# Generated by Django 3.2.7 on 2021-09-10 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Secteurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_sec', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='SouSecteurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_s_sec', models.CharField(max_length=200)),
                ('secteur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.secteurs')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_site', models.CharField(max_length=250)),
                ('s_sec', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.sousecteurs')),
            ],
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('link', models.CharField(max_length=250)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.site')),
            ],
        ),
    ]
